dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
  compiler:
    solc:
      remappings:
       - @openzeppeling=OpenZeppelin/openzeppelin-contracts@4.4.0

  dotenv: .env
  wallets:
    from_key: ${PRIVATE_KEY}